services:
  - type: web
    name: atesin-kanatlari
    env: static
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 